name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request: 
    branches: [main]
  schedule:
    - cron: '15 6 * * 0 '
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.name }}"
          echo "${{ github.ref }} is ."
      - uses: actions/chekout@v3.3.0
      
      - name : repos
        run: |
          echo "${{ github.repository }}"
          tree
